
import java.text.MessageFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.util.regex.Pattern;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Suresh Kumar
 */
public class POS extends javax.swing.JFrame {

    /**
     * Creates new form POS
     */
    public POS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jbtn9 = new javax.swing.JButton();
        jbtn1 = new javax.swing.JButton();
        jbtn8 = new javax.swing.JButton();
        jbtn7 = new javax.swing.JButton();
        jbtn4 = new javax.swing.JButton();
        jbtn5 = new javax.swing.JButton();
        jbtn6 = new javax.swing.JButton();
        jbtn3 = new javax.swing.JButton();
        jbtn2 = new javax.swing.JButton();
        jbtnDot = new javax.swing.JButton();
        jbtn0 = new javax.swing.JButton();
        jbtnC = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jbtnExit = new javax.swing.JButton();
        jbtnPrint = new javax.swing.JButton();
        jbtnPay = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();
        jbtnRemove = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtextTotal = new javax.swing.JTextField();
        jtextSubTotal = new javax.swing.JTextField();
        jtextGST = new javax.swing.JTextField();
        jPanel15 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtextChange = new javax.swing.JTextField();
        jtextDisplay = new javax.swing.JTextField();
        jcboPayment = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jbtnChips = new javax.swing.JButton();
        jbtnCocaCola = new javax.swing.JButton();
        jbtnCupNoodles = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jbtnDairyMilk = new javax.swing.JButton();
        jbtnEggs = new javax.swing.JButton();
        jbtnCookingOil = new javax.swing.JButton();
        jbtnHorlicks = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jButton45 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jbtnWheatFlour = new javax.swing.JButton();
        jbtnSoap = new javax.swing.JButton();
        jbtnShampoo = new javax.swing.JButton();
        jbtnAxe = new javax.swing.JButton();
        jbtnBiscuit = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jlblCnum = new javax.swing.JLabel();
        jtextCNum = new javax.swing.JTextField();
        jlblCname = new javax.swing.JLabel();
        jtextCName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtn9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtn9.setText("9");
        jbtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn9ActionPerformed(evt);
            }
        });
        jPanel3.add(jbtn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 100, 100));

        jbtn1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtn1.setText("1");
        jbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn1ActionPerformed(evt);
            }
        });
        jPanel3.add(jbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 100, 100));

        jbtn8.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtn8.setText("8");
        jbtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn8ActionPerformed(evt);
            }
        });
        jPanel3.add(jbtn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 100, 100));

        jbtn7.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtn7.setText("7");
        jbtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn7ActionPerformed(evt);
            }
        });
        jPanel3.add(jbtn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 100, 100));

        jbtn4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtn4.setText("4");
        jbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn4ActionPerformed(evt);
            }
        });
        jPanel3.add(jbtn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 100, 100));

        jbtn5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtn5.setText("5");
        jbtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn5ActionPerformed(evt);
            }
        });
        jPanel3.add(jbtn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 100, 100));

        jbtn6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtn6.setText("6");
        jbtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn6ActionPerformed(evt);
            }
        });
        jPanel3.add(jbtn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 100, 100));

        jbtn3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtn3.setText("3");
        jbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn3ActionPerformed(evt);
            }
        });
        jPanel3.add(jbtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 100, 100));

        jbtn2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtn2.setText("2");
        jbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn2ActionPerformed(evt);
            }
        });
        jPanel3.add(jbtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 100, 100));

        jbtnDot.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnDot.setText(".");
        jbtnDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDotActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnDot, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 100, 100));

        jbtn0.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtn0.setText("0");
        jbtn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn0ActionPerformed(evt);
            }
        });
        jPanel3.add(jbtn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 100, 100));

        jbtnC.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnC.setText("C");
        jbtnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnC, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 100, 100));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 10, 340, 470));

        jTable1.setBackground(new java.awt.Color(204, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product", "Quantity", "Amount"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, 320, 240));

        jPanel12.setBackground(new java.awt.Color(204, 255, 204));
        jPanel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel13.setBackground(new java.awt.Color(255, 255, 102));
        jPanel13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnExit.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnExit.setText("Exit");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });
        jPanel13.add(jbtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 370, 30));

        jbtnPrint.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnPrint.setText("Print");
        jbtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPrintActionPerformed(evt);
            }
        });
        jPanel13.add(jbtnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 150, 50));

        jbtnPay.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnPay.setText("Pay");
        jbtnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPayActionPerformed(evt);
            }
        });
        jPanel13.add(jbtnPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 150, 50));

        jbtnReset.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnReset.setText("Reset");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });
        jPanel13.add(jbtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 150, 50));

        jbtnRemove.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnRemove.setText("Remove");
        jbtnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRemoveActionPerformed(evt);
            }
        });
        jPanel13.add(jbtnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 150, 50));

        jPanel12.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 20, 420, 180));

        jPanel14.setBackground(new java.awt.Color(255, 255, 102));
        jPanel14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 102));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Total");
        jPanel14.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 100, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("SubTotal");
        jPanel14.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 110, 40));

        jLabel3.setBackground(new java.awt.Color(255, 255, 102));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("G.S.T");
        jPanel14.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 110, 40));

        jtextTotal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jPanel14.add(jtextTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 220, -1));

        jtextSubTotal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jtextSubTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextSubTotalActionPerformed(evt);
            }
        });
        jPanel14.add(jtextSubTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 220, -1));

        jtextGST.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jPanel14.add(jtextGST, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 220, -1));

        jPanel12.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 420, 180));

        jPanel15.setBackground(new java.awt.Color(255, 255, 102));
        jPanel15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(255, 255, 102));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Change");
        jPanel15.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 100, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 102));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Amount");
        jPanel15.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 110, 40));

        jLabel6.setBackground(new java.awt.Color(255, 255, 102));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("Payment Method");
        jPanel15.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 200, 40));

        jtextChange.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jPanel15.add(jtextChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 220, -1));

        jtextDisplay.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jtextDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextDisplayActionPerformed(evt);
            }
        });
        jPanel15.add(jtextDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 220, -1));

        jcboPayment.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jcboPayment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Credit Card" }));
        jcboPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboPaymentActionPerformed(evt);
            }
        });
        jPanel15.add(jcboPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 160, 40));

        jPanel12.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 420, 180));

        getContentPane().add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 1370, 230));

        jPanel2.setBackground(new java.awt.Color(255, 255, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnChips.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnChips.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Chips_0.jpg"))); // NOI18N
        jbtnChips.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnChipsActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnChips, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 150, 130));

        jbtnCocaCola.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnCocaCola.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/CocaCola.jpg"))); // NOI18N
        jbtnCocaCola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCocaColaActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnCocaCola, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 150, 130));

        jbtnCupNoodles.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnCupNoodles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Cup_Noodles.jpg"))); // NOI18N
        jbtnCupNoodles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCupNoodlesActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnCupNoodles, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 150, 130));

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton17.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton17.setText("7");
        jPanel4.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 150, 130));

        jButton18.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton18.setText("7");
        jPanel4.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, 130));

        jButton19.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton19.setText("7");
        jPanel4.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 150, 130));

        jButton20.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton20.setText("7");
        jPanel4.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 150, 130));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, 640, 270));

        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton29.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton29.setText("7");
        jPanel7.add(jButton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 150, 130));

        jButton30.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton30.setText("7");
        jPanel7.add(jButton30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, 130));

        jButton31.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton31.setText("7");
        jPanel7.add(jButton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 150, 130));

        jButton32.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton32.setText("7");
        jPanel7.add(jButton32, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 150, 130));

        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton33.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton33.setText("7");
        jPanel8.add(jButton33, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 150, 130));

        jButton34.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton34.setText("7");
        jPanel8.add(jButton34, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, 130));

        jButton35.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton35.setText("7");
        jPanel8.add(jButton35, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 150, 130));

        jButton36.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton36.setText("7");
        jPanel8.add(jButton36, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 150, 130));

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, 700, 470));

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 160, 700, 470));

        jbtnDairyMilk.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnDairyMilk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/dairy_milk.jpg"))); // NOI18N
        jbtnDairyMilk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDairyMilkActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnDairyMilk, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 150, 130));

        jbtnEggs.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnEggs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/eggs.jpg"))); // NOI18N
        jbtnEggs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEggsActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnEggs, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 150, 130));

        jbtnCookingOil.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnCookingOil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Refined_Sunflower_oil.jpg"))); // NOI18N
        jbtnCookingOil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCookingOilActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnCookingOil, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 150, 130));

        jbtnHorlicks.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnHorlicks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/horlicks.jpg"))); // NOI18N
        jbtnHorlicks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnHorlicksActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnHorlicks, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 150, 130));

        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton41.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton41.setText("7");
        jPanel9.add(jButton41, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 150, 130));

        jButton42.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton42.setText("7");
        jPanel9.add(jButton42, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, 130));

        jButton43.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton43.setText("7");
        jPanel9.add(jButton43, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 150, 130));

        jButton44.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton44.setText("7");
        jPanel9.add(jButton44, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 150, 130));

        jPanel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton45.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton45.setText("7");
        jPanel10.add(jButton45, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 150, 130));

        jButton46.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton46.setText("7");
        jPanel10.add(jButton46, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, 130));

        jButton47.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton47.setText("7");
        jPanel10.add(jButton47, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 150, 130));

        jButton48.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton48.setText("7");
        jPanel10.add(jButton48, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 150, 130));

        jPanel9.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, 700, 470));

        jPanel2.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 310, 700, 470));

        jbtnWheatFlour.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnWheatFlour.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/wheat_flour.jpg"))); // NOI18N
        jbtnWheatFlour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnWheatFlourActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnWheatFlour, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 150, 130));

        jbtnSoap.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnSoap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Soap.jpg"))); // NOI18N
        jbtnSoap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSoapActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnSoap, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 150, 130));

        jbtnShampoo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnShampoo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Shampoo.jpg"))); // NOI18N
        jbtnShampoo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnShampooActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnShampoo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, 150, 130));

        jbtnAxe.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnAxe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/body_spray.jpg"))); // NOI18N
        jbtnAxe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAxeActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnAxe, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 310, 150, 130));

        jbtnBiscuit.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnBiscuit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/biscuit.jpg"))); // NOI18N
        jbtnBiscuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBiscuitActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnBiscuit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, 130));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 690, 470));

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblCnum.setBackground(new java.awt.Color(255, 255, 255));
        jlblCnum.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jlblCnum.setText("Contact Number");
        jPanel1.add(jlblCnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 200, 40));

        jtextCNum.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jPanel1.add(jtextCNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 280, -1));

        jlblCname.setBackground(new java.awt.Color(255, 255, 255));
        jlblCname.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jlblCname.setText("Name");
        jPanel1.add(jlblCname, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 110, 40));

        jtextCName.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jPanel1.add(jtextCName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 280, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 260, 320, 220));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private double points;
    public void ItemCost()
    {
        double sum = 0;
        for(int i = 0; i < jTable1.getRowCount();i++)
        {
            sum = sum + Double.parseDouble(jTable1.getValueAt(i,2).toString());
        }
        jtextSubTotal.setText(Double.toString(sum));
        double cTotal1 = Double.parseDouble(jtextSubTotal.getText());
        points = cTotal1;
        
        double cTax = (cTotal1 * 0.12);
        String iTaxTotal = String.format("₹ %.2f", cTax);
        jtextGST.setText(iTaxTotal);
        
        String iSubTotal = String.format("₹ %.2f", cTotal1);
        jtextSubTotal.setText(iSubTotal);
        
        String iTotal = String.format("₹ %.2f", cTotal1 + cTax);
        jtextTotal.setText(iTotal);
    }
    private void jbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn1ActionPerformed
        String Enternumber = jtextDisplay.getText();
        
        if("".equals(Enternumber))
        {
            jtextDisplay.setText(jbtn1.getText()); 
        }
        else
        {
            Enternumber = jtextDisplay.getText() + jbtn1.getText();
            jtextDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn1ActionPerformed
    public double Change()
    {
        double sum = 0;
        double tax = 12;
        if(!("".equals(jtextDisplay.getText()))) {
        double cash = Double.parseDouble(jtextDisplay.getText());
        
        for(int i = 0; i < jTable1.getRowCount();i++)
        {
            sum = sum + Double.parseDouble(jTable1.getValueAt(i,2).toString());
        }
        
        double cTax = (sum * tax)/100;
        double cChange = (cash - (sum + cTax));
        
        return cChange;
        }
        return 0;
    }
    private void jbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn4ActionPerformed
        String Enternumber = jtextDisplay.getText();
        
        if("".equals(Enternumber))
        {
            jtextDisplay.setText(jbtn4.getText()); 
        }
        else
        {
            Enternumber = jtextDisplay.getText() + jbtn4.getText();
            jtextDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn4ActionPerformed

    private void jbtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn5ActionPerformed
        String Enternumber = jtextDisplay.getText();
        
        if("".equals(Enternumber))
        {
            jtextDisplay.setText(jbtn5.getText()); 
        }
        else
        {
            Enternumber = jtextDisplay.getText() + jbtn5.getText();
            jtextDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn5ActionPerformed

    private void jbtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn6ActionPerformed
        String Enternumber = jtextDisplay.getText();
        
        if("".equals(Enternumber))
        {
            jtextDisplay.setText(jbtn6.getText()); 
        }
        else
        {
            Enternumber = jtextDisplay.getText() + jbtn6.getText();
            jtextDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn6ActionPerformed

    private void jbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn3ActionPerformed
        String Enternumber = jtextDisplay.getText();
        
        if("".equals(Enternumber))
        {
            jtextDisplay.setText(jbtn3.getText()); 
        }
        else
        {
            Enternumber = jtextDisplay.getText() + jbtn3.getText();
            jtextDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn3ActionPerformed

    private void jbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn2ActionPerformed
        String Enternumber = jtextDisplay.getText();
        
        if("".equals(Enternumber))
        {
            jtextDisplay.setText(jbtn2.getText()); 
        }
        else
        {
            Enternumber = jtextDisplay.getText() + jbtn2.getText();
            jtextDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn2ActionPerformed

    private void jbtnDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDotActionPerformed
        if(! jtextDisplay.getText().contains("."))
        {
            jtextDisplay.setText(jtextDisplay.getText()+ jbtnDot.getText());
        }
    }//GEN-LAST:event_jbtnDotActionPerformed

    private void jbtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn0ActionPerformed
        String Enternumber = jtextDisplay.getText();
        
        if("".equals(Enternumber))
        {
            jtextDisplay.setText(jbtn0.getText()); 
        }
        else
        {
            Enternumber = jtextDisplay.getText() + jbtn0.getText();
            jtextDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn0ActionPerformed

    private void jbtnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCActionPerformed
        jtextDisplay.setText("");
        jtextChange.setText("");
    }//GEN-LAST:event_jbtnCActionPerformed

    private void jbtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn7ActionPerformed
     
        String Enternumber = jtextDisplay.getText();
        
        if("".equals(Enternumber))
        {
            jtextDisplay.setText(jbtn7.getText()); 
        }
        else
        {
            Enternumber = jtextDisplay.getText() + jbtn7.getText();
            jtextDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn7ActionPerformed

    private void jbtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn8ActionPerformed
        String Enternumber = jtextDisplay.getText();
        
        if("".equals(Enternumber))
        {
            jtextDisplay.setText(jbtn8.getText()); 
        }
        else
        {
            Enternumber = jtextDisplay.getText() + jbtn8.getText();
            jtextDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn8ActionPerformed

    private void jbtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn9ActionPerformed
        String Enternumber = jtextDisplay.getText();
        
        if("".equals(Enternumber))
        {
            jtextDisplay.setText(jbtn9.getText()); 
        }
        else
        {
            Enternumber = jtextDisplay.getText() + jbtn9.getText();
            jtextDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn9ActionPerformed

    private void jbtnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPayActionPerformed
        if(jTable1.getRowCount()==0)
        {
            JOptionPane.showMessageDialog(frame,"Please Select Items to order","Warning",JOptionPane.WARNING_MESSAGE);
        }
        else if("".equals(jtextDisplay.getText()))
        {
            JOptionPane.showMessageDialog(frame,"Please Enter Amount to pay","Warning",JOptionPane.WARNING_MESSAGE);
        }
        else if(jcboPayment.getSelectedItem().equals("Cash"))
        {
            double cChange = Change();
            if(cChange < 0)
            {
                JOptionPane.showMessageDialog(frame,"Entered Amount is not sufficient","Warning",JOptionPane.WARNING_MESSAGE);
                jtextDisplay.setText("");
            }
            else
            {
                String ChangeGiven = String.format("₹ %.2f", cChange);
                jtextChange.setText(ChangeGiven);
                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                model.addRow(new Object[]{"Gross Total","",jtextSubTotal.getText()});
                model.addRow(new Object[]{"G.S.T Added","",jtextGST.getText()});
                model.addRow(new Object[]{"Net Total","",jtextTotal.getText()});
                model.addRow(new Object[]{"Mode of Payment","",jcboPayment.getSelectedItem()});
                model.addRow(new Object[]{"Received","","₹ "+jtextDisplay.getText()});
                model.addRow(new Object[]{"Balance returned","",jtextChange.getText()});
            }
        }
        else if("Credit Card".equals(jcboPayment.getSelectedItem()))
        {
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.addRow(new Object[]{"Gross Total","",jtextSubTotal.getText()});
            model.addRow(new Object[]{"G.S.T Added","",jtextGST.getText()});
            model.addRow(new Object[]{"Net Total","",jtextTotal.getText()});
            model.addRow(new Object[]{"Mode of Payment","",jcboPayment.getSelectedItem()});
            model.addRow(new Object[]{"Credited Amount","","₹ "+jtextDisplay.getText()});
            jtextDisplay.setText("");
        }
    }//GEN-LAST:event_jbtnPayActionPerformed

    private void jbtnBiscuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBiscuitActionPerformed
        double priceOfItem = 15;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Biscuits","1 75g packet",priceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnBiscuitActionPerformed

    private void jbtnChipsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnChipsActionPerformed
        double priceOfItem = 50;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Potato Chips","1 90g Packet",priceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnChipsActionPerformed

    private void jbtnCupNoodlesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCupNoodlesActionPerformed
        double priceOfItem = 35;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Cup Noodles","1 100g Pack",priceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnCupNoodlesActionPerformed

    private void jbtnCocaColaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCocaColaActionPerformed
        double priceOfItem = 50;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"CocaCola ","1 600ml Bottle",priceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnCocaColaActionPerformed

    private void jbtnDairyMilkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDairyMilkActionPerformed
        double priceOfItem = 80;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Dairy Milk Silk","1 Choclate",priceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnDairyMilkActionPerformed

    private void jbtnEggsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEggsActionPerformed
        double priceOfItem = 35;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Eggs","1 Pack of 6",priceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnEggsActionPerformed

    private void jbtnCookingOilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCookingOilActionPerformed
        double priceOfItem = 160;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Cooking Oil","1 Litre Bottle",priceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnCookingOilActionPerformed

    private void jbtnHorlicksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnHorlicksActionPerformed
        double priceOfItem = 255;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Horlicks","1 100g Bottle",priceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnHorlicksActionPerformed

    private void jbtnWheatFlourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnWheatFlourActionPerformed
        double priceOfItem = 60;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Wheat Flour","1 kg Pack",priceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnWheatFlourActionPerformed

    private void jbtnSoapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSoapActionPerformed
        double priceOfItem = 110;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Soaps","1 Pack of 4",priceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnSoapActionPerformed

    private void jbtnShampooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnShampooActionPerformed
        double priceOfItem = 70;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Shampoo","1 75ml Bottle",priceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnShampooActionPerformed

    private void jbtnAxeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAxeActionPerformed
        double priceOfItem = 200;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Axe Body Spray","1 300ml Bottle",priceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnAxeActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        jtextChange.setText("");
        jtextGST.setText("");
        jtextTotal.setText("");
        jtextSubTotal.setText("");
        jtextDisplay.setText("");
        jtextCName.setText("");
        jtextCNum.setText("");
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jbtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPrintActionPerformed
        
        boolean warning = false;
        if(jTable1.getRowCount()==0)
        {
            warning = true;
            JOptionPane.showMessageDialog(frame,"Please Select Items to order","Warning",JOptionPane.WARNING_MESSAGE);
        }
        else if("".equals(jtextCName.getText()) && "".equals(jtextCNum.getText()))
        {
            warning = true;
            JOptionPane.showMessageDialog(frame,"Customer Name and Contact Number is required","Warning",JOptionPane.WARNING_MESSAGE);
        }
        else if("".equals(jtextCName.getText()))
        {
            warning = true;
            JOptionPane.showMessageDialog(frame,"Customer Name is required","Warning",JOptionPane.WARNING_MESSAGE);
        }
        else if(jtextCName.getText().length()>0){
            if(jtextCName.getText().contains(" "))
            {
                String[] arr = jtextCName.getText().split(" ");
                for(String str:arr)
                {
                    if(!Pattern.matches("[a-zA-Z]+",str))
                    {
                        warning = true;
                        break;
                    }
                }
                if(warning)
                {
                    JOptionPane.showMessageDialog(frame,"Customer Name is should contain only alphabets","Warning",JOptionPane.WARNING_MESSAGE);
                }
            }
            else
            {
                if(!Pattern.matches("[a-zA-Z]+",jtextCName.getText()))
                {
                    warning = true;
                    JOptionPane.showMessageDialog(frame,"Customer Name is should contain only alphabets","Warning",JOptionPane.WARNING_MESSAGE);
                }
            }
        }
        else if("".equals(jtextCNum.getText()))
        {
            warning = true;
            JOptionPane.showMessageDialog(frame,"Customer Contact number is required","Warning",JOptionPane.WARNING_MESSAGE);
        }
        else if(jtextCNum.getText().length() != 10)
        {
            warning = true;
            JOptionPane.showMessageDialog(frame,"Customer Contact number should be 10 digits","Warning",JOptionPane.WARNING_MESSAGE);
        }
        if(!warning)
        {
            points = points*(0.1);
            
            MessageFormat header = new MessageFormat("S.R.S.T Shop No 48 Main Road Anna Nagar Chennai");
            MessageFormat footer = new MessageFormat("Customer Name : "+jtextCName.getText()+" Contact Number: "+jtextCNum.getText()+" Points Earned: "
            +Double.toString(points));

            try
            {
                jTable1.print(JTable.PrintMode.NORMAL,header,footer);
            }
            catch(java.awt.print.PrinterException e)
            {
                System.err.format("No Printer Found", e.getMessage());
            }
        }
    }//GEN-LAST:event_jbtnPrintActionPerformed

    private void jbtnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRemoveActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        if(jTable1.getRowCount()==0)
        {
            JOptionPane.showMessageDialog(frame,"Please Select Items to order","Warning",JOptionPane.WARNING_MESSAGE);
        }
        else
        {
            int RemoveItem = jTable1.getSelectedRow();
            if(RemoveItem >= 0)
            {
                model.removeRow(RemoveItem);
                ItemCost();



                if(jcboPayment.getSelectedItem().equals("Cash"))
                {
                    Change();
                }
                else
                {
                   jtextChange.setText("");
                   jtextDisplay.setText("");
                }
            }
        }
    }//GEN-LAST:event_jbtnRemoveActionPerformed
    private JFrame frame;
    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        frame = new JFrame("Exit");
        if(JOptionPane.showConfirmDialog(frame,"Confirm if you want to exit","Point of Sale",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jtextSubTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextSubTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextSubTotalActionPerformed

    private void jtextDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextDisplayActionPerformed

    private void jcboPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboPaymentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcboPaymentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new POS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtn0;
    private javax.swing.JButton jbtn1;
    private javax.swing.JButton jbtn2;
    private javax.swing.JButton jbtn3;
    private javax.swing.JButton jbtn4;
    private javax.swing.JButton jbtn5;
    private javax.swing.JButton jbtn6;
    private javax.swing.JButton jbtn7;
    private javax.swing.JButton jbtn8;
    private javax.swing.JButton jbtn9;
    private javax.swing.JButton jbtnAxe;
    private javax.swing.JButton jbtnBiscuit;
    private javax.swing.JButton jbtnC;
    private javax.swing.JButton jbtnChips;
    private javax.swing.JButton jbtnCocaCola;
    private javax.swing.JButton jbtnCookingOil;
    private javax.swing.JButton jbtnCupNoodles;
    private javax.swing.JButton jbtnDairyMilk;
    private javax.swing.JButton jbtnDot;
    private javax.swing.JButton jbtnEggs;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnHorlicks;
    private javax.swing.JButton jbtnPay;
    private javax.swing.JButton jbtnPrint;
    private javax.swing.JButton jbtnRemove;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnShampoo;
    private javax.swing.JButton jbtnSoap;
    private javax.swing.JButton jbtnWheatFlour;
    private javax.swing.JComboBox<String> jcboPayment;
    private javax.swing.JLabel jlblCname;
    private javax.swing.JLabel jlblCnum;
    private javax.swing.JTextField jtextCName;
    private javax.swing.JTextField jtextCNum;
    private javax.swing.JTextField jtextChange;
    private javax.swing.JTextField jtextDisplay;
    private javax.swing.JTextField jtextGST;
    private javax.swing.JTextField jtextSubTotal;
    private javax.swing.JTextField jtextTotal;
    // End of variables declaration//GEN-END:variables
}
